require "stumpy_png"

EPSILON = 0.00001

require "./src/vector"
require "./src/color"
require "./src/quaternion"
require "./src/distribution"
require "./src/ray"
require "./src/hitable"
require "./src/hitables/*"
require "./src/transformation"
require "./src/camera"
require "./src/helper"
require "./src/material"
require "./src/bxdf"
require "./src/microfacet_distribution"
require "./src/bxdfs/*"
require "./src/bsdf"
require "./src/texture"
require "./src/background"
require "./src/backgrounds/*"
require "./src/light"
require "./src/onb"
require "./src/obj"
require "./src/scene"
require "./src/sample"
require "./src/raytracer"
require "./src/raytracers/*"
require "./src/csg"
